### ISSUE TITLE
Code Owners will be selected

### ISSUE THREAD

**Issue by damla** [Source-Pocket/source-pocket#56]
**Is your feature request related to a problem? Please describe.**

- To maintain the layout of the system, links need to be revised by `Code Owners`.

**Describe the solution you'd like**

- Select `Code Owners` for Source Pocket.

**Comment by fatihlattab** [comment]
add me 🙃

**Comment by YusufBilgin** [comment]
me too : )

**Comment by electricalgorithm** [comment]
I can be a link-reviewer :)

**Comment by damla** [comment]
We may talk about this subject on our Discord Server. I will ping you guys to set a schedule @fatihlattab @electricalgorithm @YusufBilgin 👍🏼

**Comment by Emanet** [comment]
This is the way

**Comment by AbdullahOztuurkk** [comment]
You can add me too
